[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = { version = "1.0", features = ["nightly"] }
syn = { version = "1.0", features = ["full"] }